services:
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"  
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
  server:
    build:
      context: .
      dockerfile: apps/graphql-server/Dockerfile
      args:
        NODE_VERSION: 20.18.0
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      NPM_CONFIG_PRODUCTION: "true"
      LOGGER_LEVEL: debug
      CRYPTO_SALT: salt
      CRYPTO_DEFAULT_PASSWORD_LENGTH: 10
      DATABASE_URL: "mysql://mysql:mysql@db:3306/testdb"
      GRAPHQL_SCHEMA_VISIBLE: "true"
      JWT_SECRET: secret
      JWT_EXPIRATION_TIME: 1h
