services:
  test:
    image: mysql:8.0
    ports:
      - "3307:3306"  
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
